### PR TITLE
Fix GC memory allocation in D2 builds

### LINKED ISSUE #58: D2 build logs GC memory allocation
The D2 build in #54 logs GC memory allocation:
```
2018-06-26 10:32:38,849 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command Push request on channel 'usermap' (+544 bytes)
2018-06-26 10:32:38,850 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command Push request on channel 'usermap' (+544 bytes)
2018-06-26 10:32:38,851 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command PushMulti request (+576 bytes)
2018-06-26 10:32:38,852 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command PushMulti request (+2112 bytes)
2018-06-26 10:32:38,852 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command PushMulti request (+2112 bytes)
2018-06-26 10:32:38,858 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command PushMulti request (+2112 bytes)
2018-06-26 10:32:38,858 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command Push request on channel 'usermap' (+544 bytes)
2018-06-26 10:32:38,861 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command PushMulti request (+4160 bytes)
2018-06-26 10:32:38,861 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command PushMulti request (+4160 bytes)
2018-06-26 10:32:38,862 Info [swarm.node.connection.ConnectionHandler] - Memory usage increased while handling command Push request on channel 'usermap' (+544 bytes)
```

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
Fixes #58.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
I would also edit the `.travis.yml` to add this check to CI.

**Comment by david-eckardt-sociomantic** [comment]
Green.

File: src/dmqnode/storage/engine/overflow/file/IndexFile.d [hunk 1]
```diff
@@ -237,16 +237,18 @@ class IndexFile: PosixFile
...
+                            channel.records, channel.bytes,
+                            channel.first_offset, channel.last_offset);
 
-                this.enforce(n >= 0, "error writing index");
-            });
+            this.enforce(n >= 0, "error writing index");
+        };
+
+        this.fmt_io_signal_blocker.callBlocked({
+            iterate(on_channel);
```
Comment (Geod24) [inline src/dmqnode/storage/engine/overflow/file/IndexFile.d]: Shouldn't we change the function to accept `void delegate(/* d1to2fix_inject: scope */` ...)` instead ?
IIUC the issue is that `d1to2fix` does not add scope in parameter list of delegates.

File: src/dmqnode/storage/Ring.d [hunk 2]
```diff
@@ -315,18 +315,21 @@ public class RingNode : StorageChannels
 
         override public typeof(this) pop ( ref char[] value )
         {
-            void[] allocValue ( size_t n )
+            scope allocValue = delegate void[] ( size_t n )
             {
+                if (value.length < n)
+                    enableStomping(value);
```
Comment (Geod24) [inline src/dmqnode/storage/Ring.d]: That looks weird. You `enableStomping` in the event you extend the buffer, but that is AFAIK useless because extending the buffer == reallocation (most of the time).
I would expect a single `enableStomping` call after the `length` assignment.

File: src/dmqnode/storage/Ring.d [hunk 3]
```diff
@@ -315,18 +315,21 @@ public class RingNode : StorageChannels
...
-            }
+            };
 
             if (void[] item = this.queue.pop())
             {
                  allocValue(item.length)[] = item[];
                  this.outer.dmqnode.record_action_counters.increment("popped", value.length);
             }
-            else if (this.overflow.pop(&allocValue))
+            else if (this.overflow.pop(allocValue))
```
Comment (Geod24) [inline src/dmqnode/storage/Ring.d]: Why is this necessary ? `d1to2fix` should insert `scope` [here](https://github.com/sociomantic-tsunami/dmqnode/blob/7696571f435275e939730daace651ad4ee1087e7/src/dmqnode/storage/engine/DiskOverflow.d#L731) 🤔
